// Example configuration file (DO NOT PUT REAL VALUES HERE)
const CONFIG = {
  QR_OUTPUT_FOLDER_ID: "<QR_OUTPUT_FOLDER_ID>",
  CLOUDINARY_CLOUD_NAME: "<CLOUDINARY_CLOUD_NAME>",
  CLOUDINARY_UPLOAD_PRESET: "<CLOUDINARY_UPLOAD_PRESET>",
  CLOUDINARY_API_KEY: "<CLOUDINARY_API_KEY>",
  CLOUDINARY_API_SECRET: "<CLOUDINARY_API_SECRET>"
};
